controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    joint_group_position_controller:
      type: position_controllers/JointGroupPositionController

    # joint_group_velocity_controller:
    #   type: velocity_controllers/JointGroupVelocityController

    # joint_trajectory_controller:
    #   type: joint_trajectory_controller/JointTrajectoryController

joint_group_position_controller:
  ros__parameters:
    joints:
      - joint1
      - joint2

# joint_group_velocity_controller:
#   ros__parameters:
#     joints:
#       - joint1
#       - joint2

# joint_trajectory_controller:
#   ros__parameters:
#     joints:
#       - joint1
#       - joint2
#     command_interfaces:
#       - position
#     state_interfaces:
#       - position
