controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    joint_group_position_controller:
      type: position_controllers/JointGroupPositionController

joint_group_position_controller:
  ros__parameters:
      joints:
        - joint1
